(function(){
'use strict';
const O=(text,score)=>({text,score}),Q=(facet,category,title,options)=>({facet,category,title,options});
const QUESTIONS=[
Q('anxiety','Q1. Romantic expectations','When a romantic occasion approaches, do you worry that you care about and invest in the relationship much more than your partner does?',[O('Often, especially when their reaction is less enthusiastic than I hoped.',3),O('Not at all. I trust that our emotional exchange is balanced.',1),O('Almost always. The fear that I am not equally valued leaves me anxious.',4),O('Occasionally, but I can usually settle myself quickly.',2)]),
Q('avoidance','Q2. Reaching out when you are low','When you feel discouraged, hurt, or vulnerable, is your first instinct to turn to your partner or process it alone?',[O('I gather my thoughts first, then share and seek comfort.',2),O('I carry it alone; revealing vulnerability makes me feel exposed.',4),O('I tell my partner right away—their presence gives me strength.',1),O('I retreat into my own world and rarely let them see me struggle.',3)]),
Q('anxiety','Q3. Fear of being “too much”','When you love someone deeply and want to share everyday life, do you worry that your enthusiasm might drive them away?',[O('Very strongly. I worry that my need for love will feel burdensome.',4),O('Sometimes I remind myself to adjust the pace.',2),O('Never. I express affection comfortably while allowing space.',1),O('Often. I may write a heartfelt message, hesitate, and delete it.',3)]),
Q('avoidance','Q4. Instinct to create distance','If a relationship develops quickly and your partner begins centering their life around you, do you instinctively pull back?',[O('No. I enjoy closeness that develops naturally.',1),O('I feel pressured and find ways to preserve more personal space.',3),O('Yes. When someone gets too close, my defenses activate.',4),O('I would slow the pace without rejecting closeness itself.',2)]),
Q('anxiety','Q5. Need for reassurance','How much do you need repeated words, gestures, or rituals to reassure you that your partner still loves you?',[O('Quite a lot. Without affection for a while, I begin to worry.',3),O('Not much. Our steady everyday connection reassures me.',1),O('Affection is lovely, but its absence does not make me doubt us.',2),O('Constantly. I need frequent reassurance that I am irreplaceable.',4)]),
Q('avoidance','Q6. Discussing difficult concerns','When facing a major decision or deeply personal struggle, can you explore it openly with your partner?',[O('I share only part and keep some doubts to myself.',3),O('Absolutely. My partner is the person I trust most.',1),O('Rarely. I believe major problems must be handled alone.',4),O('I discuss most things, but make a few decisions independently.',2)]),
Q('anxiety','Q7. Fear of abandonment','When your partner is busy or needs time alone, can you stay calm without wondering whether their feelings have changed?',[O('Usually, with basic trust and a simple heads-up.',2),O('It is extremely hard; even when I understand, I feel abandoned.',4),O('Completely. Everyone needs their own rhythm.',1),O('I become anxious and wonder what I did wrong.',3)]),
Q('avoidance','Q8. Beliefs about dependence','How do you feel about relying heavily on a partner for emotional or practical support?',[O('I strongly resist it. Depending on someone feels unsafe.',4),O('Healthy interdependence is natural and makes us stronger.',1),O('I minimize dependence because it feels like losing control.',3),O('Some dependence is fine while both people remain independent.',2)]),
Q('anxiety','Q9. Mismatch in desired closeness','Do you often feel that your partner cannot meet the depth or frequency of intimacy you want?',[O('No. The closeness and space between us feel comfortable.',1),O('Yes. I long to merge our lives, but they keep a barrier up.',4),O('Sometimes, but honest conversation helps us find balance.',2),O('Often. They seem distant, and I wish they would move closer.',3)]),
Q('avoidance','Q10. Sharing vulnerable experiences','How do you feel when telling your partner about childhood wounds, fears, or painful experiences?',[O('Awkward; I tend to joke or change the subject.',3),O('I need time, but can open up when trust is strong.',2),O('Strongly resistant. I do not show that side to anyone easily.',4),O('Accepted and understood; those moments feel precious.',1)]),
Q('anxiety','Q11. Vulnerability when showing love','When you express deep affection or prepare a surprise, do you fear that your partner’s response will feel underwhelming?',[O('Intensely. Possible disappointment can stop me expressing myself.',4),O('A little, but a quiet response would not affect me much.',2),O('Quite a lot. I regret reaching out if they are not equally moved.',3),O('Not at all. I share love without demanding a certain response.',1)]),
Q('avoidance','Q12. Feeling crowded by expectations','How do you feel when a partner expects frequent contact, such as a call every night or full knowledge of your schedule?',[O('It feels close, but we can discuss a pace that suits us.',2),O('Invaded and irritated; I want to shut everything off.',4),O('Cared for. We simply need to coordinate our routines.',1),O('Subtly trapped; I start looking for ways to create distance.',3)])];
const P=(icon,name,quadrant,tags,desc,radar,matchPartner,matchAdvice,quote)=>({icon,name,quadrant,tags,desc,radar,matchPartner,matchAdvice,quote});
const PERSONA_TYPES={
pure_anchor:P('🛡️','Steady Star','SECURE · DEEPLY BALANCED',['#EmotionalAnchor','#EasyCloseness','#MatureWarmth','#CreatesSafety'],'Like a constant star, you enjoy deep closeness while respecting independence. Romantic occasions are not tests, but warm chances to express gratitude and affection.',{stability:96,openness:92,sensitivity:82,boundary:90,repairability:95},'All styles—especially as an anchor for anxious partners and a safe harbor for avoidant partners.','Your security is a gift. A gentle, consistent pace can help both partners grow.','“Healthy love lets two independent souls meet freely—connected, never confined.”'),
warm_guardian:P('🌸','Warm Guardian','SECURE-ANXIOUS · EMPATHIC HEART',['#Affectionate','#HighEmpathy','#LovesRituals','#TenderHeart'],'You love generously and notice emotional nuance. You enjoy making a partner feel cherished. You may need extra affection sometimes, but self-awareness helps you return to balance.',{stability:82,openness:94,sensitivity:90,boundary:78,repairability:92},'Steady Star / Grounded Pine','Name what you want directly instead of waiting for your partner to guess.','“Romance lives in every moment that says: I noticed you, and you matter.”'),
steady_pine:P('🌲','Grounded Pine','SECURE-AVOIDANT · QUIET PROTECTOR',['#Dependable','#ClearBoundaries','#LoveInAction','#QuietPresence'],'Like a quiet pine, you may not lead with sweet words, but you show up when it matters. You value calm, boundaries, and sincere time over performative romance.',{stability:90,openness:72,sensitivity:75,boundary:94,repairability:86},'Steady Star / Warm Guardian','Let some hidden affection become visible. Even “I’m glad you’re here” can bring real warmth.','“Deep love lives in every steady act of care.”'),
blazing_tide:P('🌊','Blazing Tide','ANXIOUS · DEEPLY IMMERSED',['#CravesReassurance','#HighlySensitive','#AllIn','#NeedsConnection'],'Your love moves like a powerful tide. A delayed reply or flat tone may awaken fear. You are not unreasonable—you simply care deeply and fear losing the bond.',{stability:52,openness:88,sensitivity:96,boundary:48,repairability:76},'Steady Star—patient, consistent, and reassuring.','Return some attention to yourself. Your worth does not depend on immediate replies.','“You deserve a love that does not keep you guessing.”'),
devoted_dove:P('🕊️','Devoted Dove','ANXIOUS · SELF-SILENCING GIVER',['#PeoplePleasing','#AvoidsConflict','#OverAccommodating','#WantsToBeSeen'],'You may hide your hopes to avoid being a burden. You give continuously to keep love stable while longing for someone to notice your unspoken needs.',{stability:60,openness:65,sensitivity:92,boundary:42,repairability:82},'Warm Guardian / Steady Star','Expressing a need is not selfish; it gives your partner a chance to love you well.','“Real love makes room for your truth and your needs.”'),
island_glacier:P('🧊','Island Glacier','DISMISSIVE-AVOIDANT · SELF-PROTECTIVE',['#FiercelyIndependent','#EmotionallyCool','#DefensiveWalls','#SelfReliant'],'You keep emotion beneath the surface. Intense expectations can feel suffocating, and relying only on yourself seems safest. Your defenses rise when someone approaches your inner world.',{stability:78,openness:32,sensitivity:60,boundary:98,repairability:50},'Steady Star / Grounded Pine—patient and respectful of space.','One small vulnerability with someone trustworthy can let warmth return.','“Independence can be armor—do not let it keep all warmth out.”'),
solo_falcon:P('🦅','Solo Falcon','DISMISSIVE-AVOIDANT · FREE THINKER',['#ValuesPeace','#ClearBoundaries','#RejectsControl','#ContentAlone'],'You are self-directed and want intimacy to feel easy and spacious. Emotional pressure and staged romance repel you. If togetherness is not freer than solitude, you would rather fly solo.',{stability:85,openness:45,sensitivity:68,boundary:92,repairability:62},'Steady Star / Grounded Pine','Choose moments to land beside your partner. Healthy reliance adds depth without taking freedom.','“The best companions fly freely and still find each other.”'),
thorny_aurora:P('✨','Thorned Aurora','FEARFUL-AVOIDANT · PUSH-PULL HEART',['#DeepFeelings','#ProtectiveSpikes','#TestsThenRetreats','#LongsToBeKnown'],'You long for profound love, yet fear makes you retreat when it comes close. The pull between approaching and pushing away can be exhausting.',{stability:48,openness:58,sensitivity:98,boundary:62,repairability:60},'Steady Star—patient, accepting, and unwavering.','Acknowledge both fear and longing. Build trust in small steps and give love time to feel safe.','“May gentleness soften every old defense.”')};
const QUOTES=[['','At the touch of love everyone becomes a poet.','— Plato'],['','Gravitation is not responsible for people falling in love.','— Albert Einstein'],['','All that I understand, I understand only because I love.','— Leo Tolstoy'],['','The moon is beautiful tonight.','— Natsume Sōseki'],['','To love and be loved is to feel the sun from both sides.','— David Viscott'],['','We are most alive when we are in love.','— John Updike'],['','Love is composed of a single soul inhabiting two bodies.','— Aristotle'],['','Where there is love there is life.','— Mahatma Gandhi'],['','Whatever our souls are made of, his and mine are the same.','— Emily Brontë'],['✨ Three questions left—your coordinates are almost ready ✨','My heart is, and always will be, yours.','— Jane Austen'],['💖 Almost there—two questions left','Love is looking outward together in the same direction.','— Antoine de Saint-Exupéry'],['🚀 Final question—your relationship report is next','Mature love says: “I need you because I love you.”','— Erich Fromm']];
let index=0,answers=[];const $=id=>document.getElementById(id),screens=['start-screen','quiz-screen','loading-screen','result-screen'].map($);function show(t){screens.forEach(x=>x.classList.remove('active'));t.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
$('start-btn').onclick=()=>{index=0;answers=[];show($('quiz-screen'));render()};$('retest-btn').onclick=()=>{index=0;answers=[];show($('start-screen'))};$('prev-btn').onclick=()=>{if(index){index--;render()}};$('close-modal-btn').onclick=()=>$('image-modal').classList.remove('active');$('save-btn').onclick=screenshot;
function render(){const x=QUESTIONS[index],z=QUOTES[index];$('curr-q').textContent=index+1;$('progress-fill').style.width=`${(index+1)/12*100}%`;$('prev-btn').style.display=index?'inline-flex':'none';$('quote-cn').textContent=z[1];$('quote-original').style.display='none';$('quote-author').textContent=z[2];$('quote-countdown').textContent=z[0];$('quote-countdown').style.display=z[0]?'flex':'none';$('quote-card').classList.toggle('encourage',!!z[0]);$('q-category').textContent=x.category;$('q-title').textContent=x.title;$('options-grid').innerHTML='';x.options.forEach((a,i)=>{const b=document.createElement('button');b.className='option-btn'+(answers[index]===a.score?' selected':'');b.innerHTML=`<span class="opt-prefix">${'ABCD'[i]}</span><span class="opt-text">${a.text}</span>`;b.onclick=()=>pick(b,a.score);$('options-grid').appendChild(b)})}
function pick(b,s){$('options-grid').querySelectorAll('.option-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');answers[index]=s;setTimeout(()=>{index++;index<12?render():finish()},260)}
function finish(){show($('loading-screen'));setTimeout(()=>$('loading-step-text').textContent='Locating your profile among eight attachment patterns…',600);setTimeout(calculate,1300)}
function calculate(){let a=0,v=0;QUESTIONS.forEach((x,i)=>x.facet==='anxiety'?a+=answers[i]||2:v+=answers[i]||2);a=Math.round((a-6)/18*100);v=Math.round((v-6)/18*100);const p=a<50&&v<50?(a<35&&v<35?PERSONA_TYPES.pure_anchor:a>=35?PERSONA_TYPES.warm_guardian:PERSONA_TYPES.steady_pine):a>=50&&v<50?(v<30?PERSONA_TYPES.blazing_tide:PERSONA_TYPES.devoted_dove):a<50&&v>=50?(v>=70?PERSONA_TYPES.island_glacier:PERSONA_TYPES.solo_falcon):PERSONA_TYPES.thorny_aurora;result(p,a,v);show($('result-screen'))}
function result(p,a,v){$('serial-id').textContent=`NO.2026-QIXI-EN-${Math.floor(1000+Math.random()*9000)}`;['icon','quadrant','name','desc','quote'].forEach(k=>$(`persona-${k}`).textContent=p[k]);$('persona-tags').innerHTML=p.tags.map(x=>`<span class="tag-item">${x}</span>`).join('');$('anxiety-val').textContent=a+'%';$('anxiety-fill').style.width=a+'%';$('avoidance-val').textContent=v+'%';$('avoidance-fill').style.width=v+'%';const l={stability:'🛡️ Emotional Stability',openness:'💬 Vulnerability & Openness',sensitivity:'🚨 Relationship Sensitivity',boundary:'🏰 Personal Boundaries',repairability:'🩹 Empathy & Repair'};$('radar-bars-container').innerHTML=Object.entries(l).map(([k,n])=>`<div class="radar-bar-item"><span class="radar-label">${n}</span><div class="radar-track"><div class="radar-fill" style="width:${p.radar[k]}%"></div></div><span class="radar-val">${p.radar[k]}%</span></div>`).join('');$('match-partner').textContent=p.matchPartner;$('match-advice').textContent=p.matchAdvice}
function screenshot(){const b=$('save-btn');b.disabled=true;b.innerHTML='<span>📸 Creating HD image…</span>';if(typeof html2canvas!=='function'){alert('Please use your device screenshot feature.');b.disabled=false;return}html2canvas($('result-card-box'),{scale:2,useCORS:true,backgroundColor:'#0f1123',logging:false}).then(c=>{const d=c.toDataURL('image/png');$('generated-img').src=d;$('download-link').href=d;$('download-link').download=`Qixi_Attachment_Report_${Date.now()}.png`;$('image-modal').classList.add('active');b.disabled=false;b.innerHTML='<span>Save HD Report Card</span>'}).catch(()=>{alert('The image could not be generated. Please take a screenshot instead.');b.disabled=false})}
})();
